[package]
name = "jbs"
description = "Toolkit for Rapid Application Development"
homepage = "https://github.com/bfren/jeebs-rs"
documentation = "https://github.com/bfren/jeebs-rs"
repository = "https://github.com/bfren/jeebs-rs"
readme = "README.md"
version = "0.1.0-beta.23120801"
edition = "2021"
license = "MIT"

[dependencies]
